### ISSUE TITLE
Bug: Multiline string identified as "too long" because total length exceeds terminal width

### ISSUE THREAD

**Issue by KodiCraft** [liambloom/command-line-draw#1]
Title is self-explanatory, when checking if a string is too long to be written, its full length is read as if it was the width even though it could have multiple lines and therefore actually be able to be displayed correctly. A fix for this would be checking if any individual line in the string exceeds the maximum width and checking if the total number of lines exceeds the maximum height

**Comment by liambloom** [comment]
Thanks for bringing this to my attention. I will fix this soon (if not later today, then at most within the next week).

**Comment by liambloom** [comment]
I believe I have fixed the issue with commit 0035bd435156132b5e01167e862b62ba146064b5, which I have published to npm as version `1.2.3`.
